name: cd

on:
<<<<<<< HEAD
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: ["dev"]
=======
  push:
    branches: [ "dev" ]
>>>>>>> 03bb9199f10c1cb3614149d38efb73c828721c31

concurrency:
  group: cd-dev
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        run: |
          IMAGE_BASE=ghcr.io/${{ github.repository_owner }}/blankspace
          SHA=${GITHUB_SHA::7}

          docker build -t $IMAGE_BASE:latest -t $IMAGE_BASE:sha-$SHA .
          docker push $IMAGE_BASE:latest
          docker push $IMAGE_BASE:sha-$SHA

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Deploying commit ${{ github.sha }}"
            ~/deploy.sh